### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by lopippo** [PiotrRadzinski/envemind#2]
Greetings,

I have run this command:
pip install envemind --user

but I got this error and I do not understand what is going on.

ERROR: Could not find a version that satisfies the requirement envemind (from versions: none)
ERROR: No matching distribution found for envemind

Would you help me, please ?

Sincerely
Filippo

**Comment by PiotrRadzinski** [comment]
Hey again!
As I noticed, it does not always work properly on MacBooks (is that your case?). @michalsta should fix that very soon :)
Sincerely,
Piotr

**Comment by lopippo** [comment]
Greetings, Piotr,
thank you for your quick responses. No, I am using Debian (testing). I know my Python setup is fine (I can run IsoSpecPy fine in a project).
Sincerely,
Filippo

**Comment by michalsta** [comment]
Hi,

There was a very crucial "/" missing in the install instructions, the second command should be: 

```
pip install envemind/ --user
```

I updated the README.md so this thing should work fine now.
